version: '3'
services:
  redis:
    image: redis
    # network_mode: host
    networks:
      - tl_network
    volumes:
      - $REDIS_STORE:/data
    ports:
      - $ODB_REDIS_PORT:$ODB_REDIS_PORT  # this is for testing, for prod we want docker networking.
    command:
      redis-server --bind $ODB_REDIS_BIND --port $ODB_REDIS_PORT
          --dbfilename db.rdb --dir /data --save 900 1 --save 300 10 --save 60 10000

  testlooper:
    build: .docker
    depends_on:
      - redis
    networks:
      - tl_network
    # network_mode: host
    ports:
      - $TL_HTTP_PORT:$TL_HTTP_PORT
    volumes:
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/testlooper
    command:
      /bin/bash run_tl.sh
networks:
  tl_network:
    driver: bridge
