version: 1.0
image:
     docker:
        dockerfile: .testlooper/environments/plan-generation/Dockerfile
        with-docker: true

variables:
    PYTHONPATH: ${REPO_ROOT}

command:
    python .testlooper/generate_test_plan.py  --out ${TEST_PLAN_OUTPUT}
