version: 1.0
name: testlooper
primary-branch: will-deliberately-failing-tests
image:
     docker:
       dockerfile: .testlooper/environments/Dockerfile.setup
       # image: testlooper:latest
       with-docker: true

variables:
    PYTHONPATH: ${REPO_ROOT}

command:
    python .testlooper/generate_test_plan.py  --output ${TEST_PLAN_OUTPUT}
