#!/usr/bin/env python
# Reads the pyproject.toml file and generates a requirements.txt file
import toml

deps = toml.load("../pyproject.toml")["project"]["dependencies"]

with open("requirements.txt", "w") as f:
    f.write("# This file is autogenerated from pyproject.toml\n")
    f.write("\n".join(deps))
