# tells testlooper where to look for a repo, and which ports to host its various services on.

repo_path: "/home/willg/Dev/testlooper-test"
# repo_path: "/home/willg/Dev/test-looper"
config_path: ".testlooper/config.yaml"
# token: ""
http_port: 8001
odb_port: 8021
log_level_name: "ERROR"
git_watcher_port: 8999
num_workers: 16
branch_prefix:
